# Macros

PROGRAM = pilapv
COMPILER = g++
FLAGS = -g

# Explicit rules


pilav.o: nodopv.o pilav.cpp
	${COMPILER} ${FLAGS} -c pilav.cpp nodopv.o

nodopv.o: nodopv.cpp
	${COMPILER} ${FLAGS} -c nodopv.cpp

